redis:
  addr: "127.0.0.1:6379"
  password: "314159ll"
  DB: 0
  poolSize: 30
  minIdleConn: 30

port:
  server: ":9001"
  udp: 3000

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

notice:
  news: "今天没有什么新闻,祝大家心想事成~"

path:
  index: "/Users/luliang/GoLand/local_imessage/index.html"
  login: "/Users/luliang/GoLand/local_imessage/views/user/login.html"
  toRegister: "/Users/luliang/GoLand/local_imessage/views/user/register.html"
  unRegister: "/Users/luliang/GoLand/local_imessage/views/user/unregister.html"
  static: "/Users/luliang/GoLand/local_imessage/asset/"
  LoadHTMLGlob: "/Users/luliang/GoLand/local_imessage/views/**/*"

