mysql:
  dns: root:791975457@qq.com@tcp(127.0.0.1:3306)/ginchat?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: "r-bp13spatn5nmym8xqnpd.redis.rds.aliyuncs.com:6379"
  password: "r-bp13spatn5nmym8xqn:791975457@qqcom"
  DB: 1
  poolSize: 30
  minIdleConn: 30

port:
  server: ":9000"
  udp: 3001

timeout:
  DelayHeartbeat: 3   #延迟心跳时间  单位秒
  HeartbeatHz: 30   #每隔多少秒心跳时间
  HeartbeatMaxTime: 30000  #最大心跳时间  ，超过此就下线
  RedisOnlineTime: 4  #缓存的在线用户时长   单位H

config:
  app: "welcome to use viper!"