info:
  contact: {}
paths:
  /chat:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 用户模块
  /contact/addFriend:
    post:
      parameters:
      - description: 发起请求的用户ID
        in: formData
        name: userId
        type: string
      - description: 目标用户ID
        in: formData
        name: targetId
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 添加好友
      tags:
      - 用户模块
  /contact/addMan:
    post:
      parameters:
      - description: 操作者的ID
        in: formData
        name: operator
        type: string
      - description: 群组ID
        in: formData
        name: groupId
        type: string
      - description: 待添加管理员的ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 群主添加userId为群管理员
      tags:
      - 用户模块
  /contact/blockFriend:
    post:
      parameters:
      - description: 发起请求的用户ID
        in: formData
        name: userId1
        type: string
      - description: 待删除的好友ID
        in: formData
        name: userId2
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "删除失败!"}'
          schema:
            type: string
      summary: 拉黑好友
      tags:
      - 用户模块
  /contact/createGroup:
    post:
      parameters:
      - description: 群主用户ID
        in: formData
        name: ownerId
        type: string
      - description: 群组名称
        in: formData
        name: groupName
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "创建失败!"}'
          schema:
            type: string
      summary: 创建群聊
      tags:
      - 用户模块
  /contact/deMemberFromGroup:
    post:
      parameters:
      - description: 操作者的ID
        in: formData
        name: operator
        type: string
      - description: 群组ID
        in: formData
        name: groupId
        type: string
      - description: 待删除成员的ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 从群聊中删除成员
      tags:
      - 用户模块
  /contact/deleteFriend:
    post:
      parameters:
      - description: 发起请求的用户ID
        in: formData
        name: userId1
        type: string
      - description: 待删除的好友ID
        in: formData
        name: userId2
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "删除失败!"}'
          schema:
            type: string
      summary: 删除好友
      tags:
      - 用户模块
  /contact/deleteGroup:
    post:
      parameters:
      - description: 操作者的ID
        in: formData
        name: operator
        required: true
        type: string
      - description: 群组ID
        in: formData
        name: groupId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 群主解散群
      tags:
      - 用户模块
  /contact/friendsOnlineList:
    post:
      parameters:
      - description: userId
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 好友在线列表
      tags:
      - 用户模块
  /contact/getContactList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有关系
      tags:
      - 用户模块
  /contact/getGroupList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取群的列表
      tags:
      - 用户模块
  /contact/joinGroup:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      - description: 群组ID
        in: formData
        name: groupId
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "加入失败!"}'
          schema:
            type: string
      summary: 加入群聊
      tags:
      - 用户模块
  /contact/outGroup:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      - description: 群组ID
        in: formData
        name: groupId
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 退群
      tags:
      - 用户模块
  /contact/searchUsersByGroupId:
    post:
      parameters:
      - description: 群组ID
        in: formData
        name: groupId
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 按照groupId 找到所有的群成员
      tags:
      - 用户模块
  /contact/unRegister:
    post:
      parameters:
      - description: userId
        in: formData
        name: userId
        type: string
      - description: password
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 注销账号
      tags:
      - 用户模块
  /friendsList:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "获取列表失败"}'
          schema:
            type: string
      summary: 好友列表
      tags:
      - 用户模块
  /groupsList:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "获取失败"}'
          schema:
            type: string
      summary: 加载群聊列表
      tags:
      - 用户模块
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取首页
      tags:
      - 首页
  /listInOnePage:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: 'owner": {...}, "contactList": [...], "onLineList": [...],
            "groupList": [...]}'
          schema:
            type: string
      summary: 给前端呈现列表
      tags:
      - 界面模块
  /toRegister:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 跳转到注册页面
      tags:
      - 首页
  /user/createUser:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: username
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 确认密码
        in: formData
        name: Identity
        type: string
      - description: 电话号码
        in: formData
        name: phone
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "新增用户失败!"}'
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/deleteUser:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "删除用户失败!"}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取所有用户
      tags:
      - 用户模块
  /user/login:
    post:
      parameters:
      - description: 手机号码
        in: formData
        name: phone
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "登录失败"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户模块
  /user/updateUser:
    post:
      parameters:
      - description: 用户ID
        in: formData
        name: userId
        type: string
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: 'code": -1, "message": "修改用户失败!"}'
          schema:
            type: string
      summary: 修改昵称和密码
      tags:
      - 用户模块
swagger: "2.0"
